apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-custom-pipeline
spec:
  params:
    - name: salary
      type: string
    - name: expenses
      type: string
  tasks:
    - name: task-1
      taskRef:
        name: task-1
    - name: task-2
      runAfter:
        - task-1
      taskRef:
        name: task-2
      params:
        - name: salary
          value: $(params.salary)
        - name: expenses
          value: $(params.expenses)